language: groovy
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_86c85184f8a5_key -iv $encrypted_86c85184f8a5_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- sudo apt-get update -qq
- sudo apt-get install -qq xmlindent
script:
- "./grailsw test-app unit: integration:"
- "./grailsw test-app functional: 'org.zenboot.portal.api.**.*' -inline"
#- echo "n" | ./grailsw run-app &
#- sleep 120
#- cd ./zenboot-scripts/internal/scripts/sanity-restcheck && ./010_sanity-restcheck.sh
#  && cd ../../../..
- ./grailsw war
notifications:
  email:
  - k9ert@gmx.de
  slack: yrpm:rDezlAPq20RKGIp10YUeHRnq
deploy:
  provider: releases
  api_key:
    secure: O/57Mm3YYVSeyPlOJYA0jbkmrGMP3Et3eYS12ztCG0S1Duna1/2Ni/v5h/1z1KYvFnV0mtWYwDHQSPJ89R1QUzVKARFkYAAgJt5IjgXnQmsygSxganE8uG37WDh/+XqODw6/oUQp6isJ6VeoIZ/TMfyfm8uM2Udh0AAdafcYEvI=
  skip_cleanup: true
  file: target/zenboot.war
  on:
    repo: hybris/zenboot
    tags: true
    all_branches: true
